import { makeStyles } from '@material-ui/core';

const useListStyles = makeStyles((theme) => ({
  list: {
    marginBottom: theme.spacing(2),
    marginTop: '2rem',
  },
  listItem: {
    backgroundColor: 'white',
    borderRadius: '8px 8px 0px 0px',
  },
  listInfo: {
    background: '#EAE8FE',
    borderRadius: '0px 0px 8px 8px',
    marginBottom: '3rem',
  },
  listInfoText: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '21px',
    textAlign: 'center',
    color: '#8463E7',
    mixBlendMode: 'normal',
  },
  listAddContact: {
    background: '#EAE8FE',
    border: '1px solid #835BF9',
    boxSizing: 'border-box',
    borderRadius: '8px',
    width: '45px',
    height: '45px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'baseline',
    color: '#794BFF',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '30px',
    lineHeight: '41px',
    textAlign: 'center',
    padding: 0,
  },
  listAvatarContainer: {
    marginRight: '3rem',
  },
  avatarContainer: {
    position: 'absolute',
    top: '-15px',
    display: 'flex',
    justifyContent: 'center',
    background: `linear-gradient(188.8deg, #FA5D75 6.7%, rgba(120, 100, 246, 0.67) 65.76%)`,
    border: '1px solid #FFFFFF',
    boxSizing: 'border-box',
    width: '85px',
    height: '85px',
    borderRadius: '100%',
    alignItems: 'center',
    clip: 'rect(0px, 100px, 100px, 10px)',
    transform: 'rotate(48deg)',
  },
  avatarTrust: {
    position: 'absolute',
    top: '-30px',
    left: '45px',
    background: '#6A3EEA',
    width: '27px',
    height: '27px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '100%',
    zIndex: 1,
    color: '#FFFFFF',
  },
  listAvatarLarge: {
    width: theme.spacing(9.3),
    height: theme.spacing(9.3),
    position: 'absolute',
    top: '-10px',
    left: '20px',
  },
}));

export default useListStyles;
